version: '3.7'

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: "reddit-db"
      MONGO_INITDB_ROOT_USERNAME: ${ROOTUSER}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOTPASS}
    ports:
      - "27017:27017"

  nodejs:
    build: .
    command: ["npm", "test"]
    # command: ["node", "app.js"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOTUSER}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOTPASS}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - "db"
